### ISSUE TITLE
Crashes if a file used in a project is moved

### ISSUE THREAD

**Issue by whitequark** [CauldronDevelopmentLLC/OpenSCAM#115] opened 2015-01-05 22:46 UTC
With the following log:
```
22:45:16:ERROR:Exception: Accessing './Downloads/1st_side(engraving).tap': No such file or directory
22:45:16:ERROR:Exception: SmartPointer: Can't dereference a NULL pointer!
```

**Comment by jcoffland** [comment] 2015-01-06 00:16
I'm having trouble reproducing this.  What version if OpenSCAM and what operating system are you using?  Also, what were the circumstances?  Can you give me a step-by-step way of reproducing this bug?

**Comment by whitequark** [comment] 2015-01-06 00:20
OpenSCAM 0.2.5 on Debian wheezy.

To reproduce:
1. add any g-code file to the project
2. close OpenSCAM
3. delete the file
4. run OpenSCAM as `openscam foo.xml`, where `foo.xml` is the project file

**Comment by jcoffland** [comment] 2015-01-06 01:20
This seems to be fixed in the latest code.  I'm working on a new release.

Thanks for the report.

**Closed by jcoffland** 2015-01-06 01:20 UTC
Labels: bug
