### ISSUE TITLE
Export to STL Crash on windows 7 pro 64 french

### ISSUE THREAD

**Issue by Elieheloua** [CauldronDevelopmentLLC/OpenSCAM#146] opened 2015-07-01 00:22 UTC
I know issu number 77  is close, but export to stl crash after save.
Mon pc : 
win 7 pro français 64 bit 
16 G0 RAM

Merci

Elie

**Comment by jcoffland** [comment] 2015-07-01 00:52
This is a duplicate of #81.

**Closed by jcoffland** 2015-07-01 00:52 UTC
